version: "3"

services:
  #  front:
  #    build:
  #      context: ./front
  #      dockerfile: Dockerfile
  #    ports:
  #      - '5173:5173'
  #    depends_on:
  #      - redis
  #      - postgres
  #      - api

  #  api:
  #    build:
  #      context: ./api
  #      dockerfile: Dockerfile
  #    ports:
  #      - '8080:8080'
  #    depends_on:
  #      - redis
  #      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "login"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  redis-ui:
    image: rediscommander/redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
