openapi: 3.0.3
info:
  title: API Title
  version: 1.0.3
  description: API for todos
  contact:
    name: Ayaan
    email: alexeevayaan@gmail.com
servers:
  - url: http://localhost:8080/v1
    description: Local server
paths:
  /todo:
    post:
      tags:
        - Todo
      operationId: createTodo
      summary: Create a new Todo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoInput'
      responses:
        200:
          description: Todo created
          content:  
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTodoOutput'
        400:
          description: Bad request
          content:  
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /todo/{id}:
    get:
      tags:
        - Todo
      operationId: getTodoById  
      summary: Get a todo by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Todo's ID  
          example: 6a44a969-8a94-4e1c-9fe2-32dfe521fa90
      responses:
        200:
          description: Todo retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTodoOutput'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - Todo
      operationId: deleteTodoById  
      summary: Delete a todo by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Todo's ID  
          example: 6a44a969-8a94-4e1c-9fe2-32dfe521fa90
      responses:
        204:
          description: Todo deleted
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    CreateTodoInput:
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string  
          description: Title of the todo
          example: Hi, i'm from Sa
        description:
          type: string  
          description: Description of the todo
          example: I'm Golang, React, React Native Developer, please i need work.
    CreateTodoOutput:
      type: object
      required:
        - id
      properties:
        id: 
          type: string  
          description: ID of the created todo
          example: 6a44a969-8a94-4e1c-9fe2-32dfe521fa90
          format: uuid
    GetTodoOutput:
      type: object
      required:
        - id
        - created_at
        - updated_at
        - title
        - description
        - completed
      properties:
        id:
          type: string  
          description: ID of the created todo
          example: 6a44a969-8a94-4e1c-9fe2-32dfe521fa90
          format: uuid
        created_at:
          type: string
          description: DateTime when the todo was created
          example: 2025-10-01T00:00:00Z
          format: date-time
        updated_at:
          type: string
          description: DateTime when the todo was updated
          example: 2025-10-01T00:00:00Z
          format: date-time
        title:
          type: string  
          description: Title of the todo
          example: Hi, i'm from Sa
        description:
          type: string  
          description: Description of the todo
          example: I'm Golang, React, React Native Developer, please i need work.
        completed:
          type: boolean
          description: Status of the todo
          example: false
    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error Message
      example:
        error:
          error: Todo not found    
          